version: "3.3"

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
        - spring-newbank-network

networks:
  spring-newbank-network:
    driver: bridge