version: '3.8'

services:
  payment-gateway-service:
    restart: always
    image: "newbank/payment-gateway"
    container_name: "payment-gateway-service"
    env_file:
      - .env
    ports:
      - "5002:8080"
    depends_on:
      gateway-db:
          condition: service_healthy
    environment:
      - CCN_WITH_PORT=${CCN_WITH_PORT}
      - COSTUMER_WITH_PORT=${COSTUMER_WITH_PORT}
      - CCN_SERVICE=${CCN_SERVICE}
      - COSTUMER_SERVICE=${COSTUMER_SERVICE}
      - POSTGRES_HOST=gateway-db:5432
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - spring-newbank-network

  gateway-db:
    image: postgres:15.2
    container_name: "gateway-db"
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - spring-newbank-network
    healthcheck:
      #CHANGE 1: this command checks if the database is ready, right on the source db server
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: "my-nginx"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - payment-gateway-service
    networks:
      - spring-newbank-network

networks:
  spring-newbank-network:
    external: true

