version: "3.3"

services:
  fees-calculator-service:
    image: "newbank/fees-calculator"
    container_name: "fees-calculator-service"
    env_file:
      - .env
    ports:
      - 5006:8080
    environment:
      - CCN_WITH_PORT=${CCN_SERVICE}:8080
      - COSTUMER_WITH_PORT=${COSTUMER_SERVICE}:8080
      - POSTGRES_HOST=${POSTGRES_DB}:5432
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - spring-newbank-network
    # the postgres DB to be connected to the backend (watch out: no volume specified, everything can be lost)
#  gateway-db:
#     image: postgres:15.2
#     container_name: "gateway-db"
#     env_file:
#       - .env
#     environment:
#       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#       - POSTGRES_USER=${POSTGRES_USER}
#       - POSTGRES_DB=${POSTGRES_DB}
#     networks:
#       - spring-newbank-network
networks:
  spring-newbank-network:
    external: true