version: '3.8'

services:
  business-integrator-service:
    restart: always
    image: "newbank/business-integrator"
    container_name: "business-integrator-service"
    mem_limit: 1g
    cpus: 2
    env_file:
      - .env
    ports:
      - "5012:8080"
    depends_on:
      - postgresql-master
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql-master:5432/my_database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=my_database_password
    networks:
      - spring-newbank-network


networks:
  spring-newbank-network:
    external: true
