version: '3.1'
services:

  metrics-service:
    image: "newbank/metrics-service"
    container_name: "metrics-service"
    ports:
      - "3003:8080"
    restart: on-failure
    networks:
      - spring-newbank-network
    environment:
      - BUSINESS_INTEGRATOR_WITH_PORT=${BUSINESS_INTEGRATOR_SERVICE}:8080
      - MONGO_DB_HOST=${MONGO_HOST}
      - MONGO_DB_PORT=${MONGO_PORT}
      - MONGO_DB_NAME=${MONGO_DB}
networks:
  spring-newbank-network:
    external: true