version: "3.3"

services:
  payment-service:
    image: "newbank/payment-processor"
    container_name: "payment-service"
    ports:
      - 5004:8080
    environment:
      - CCN_WITH_PORT=${CCN_SERVICE}:8080
      - COSTUMER_WITH_PORT=${COSTUMER_SERVICE}:8080
      - EXTERNALBANK_WITH_PORT=${EXTERNAL_BANK_SERVICE}:8080
    networks:
      - spring-newbank-network
    # the postgres DB to be connected to the backend (watch out: no volume specified, everything can be lost)

networks:
  spring-newbank-network:
    external: true