scrape_configs:
  - job_name: 'paymentGatewayMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:80']
        labels:
          application: 'PaymentGateway Application'

  - job_name: 'customerCareMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:5003']
        labels:
          application: 'CustomerCare Application'