scrape_configs:
  - job_name: 'paymentGatewayMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:80']
        labels:
          application: 'PaymentGateway Application'

  - job_name: 'customerCareMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:5003']
        labels:
          application: 'CustomerCare Application'
  - job_name: "paymentGatewayMetrics1"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:5060']
        labels:
          application: 'PaymentGateway Application'
  - job_name: "paymentGatewayMetrics2"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:5061']
        labels:
          application: 'PaymentGateway Application'

  - job_name: "paymentServiceMetrics"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:5004']
        labels:
          application: 'PaymentProcessor Application'
  - job_name: "paymentSettlementMetrics"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:5008']
        labels:
          application: 'PaymentSettlement Application'
  - job_name: "feeCalculatorMetrics"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:5005']
        labels:
          application: 'FeeCalculator Application'
  - job_name: "transactionServiceMetrics"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:4999']
        labels:
          application: 'TransactionService Application'
