version: '3.1'
services:
  cassandra:
    image: cassandra
    container_name: cassandra
    ports:
      - "9042:9042"
    networks:
      - spring-newbank-network

  transactions-service:
    image: "newbank/transactions-service"
    container_name: "transactions-service"
    ports:
      - "4999:8080"
    depends_on:
      - cassandra
    environment:
      - CASSANDRA_HOST=cassandra
    restart: on-failure
    networks:
      - spring-newbank-network

networks:
  spring-newbank-network:
    external: true