version: '3.1'
services:

  transactions-service:
    image: "newbank/transactions-service"
    container_name: "transactions-service"
    mem_limit: 1g
    cpus: 2
    ports:
      - "4999:8080"

    networks:
      - spring-newbank-network
    environment:
      - POSTGRES_HOST=transaction-db

  transaction-db:
    image: postgres
    container_name: "transaction-db"
    mem_limit: 1g
    cpus: 2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_DB=transactions-db
    networks:
      - spring-newbank-network




networks:
  spring-newbank-network:
    external: true