version: '3.1'
services:

  transactions-service:
    image: "newbank/transactions-service"
    container_name: "transactions-service"
    mem_limit: 1g
    cpus: 2
    ports:
      - "4999:8080"

    networks:
      - spring-newbank-network
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}




networks:
  spring-newbank-network:
    external: true