version: '3.8'

services:
  payment-gateway-authorizer-service:
    restart: always
    image: "newbank/payment-gateway-authorizer"
    container_name: "payment-gateway-authorizer-service"
    env_file:
      - .env
    ports:
      - "3501:8080"
    depends_on:
      - gateway-db1
      - gateway-db2
      - postgresql-slave
    environment:
      - CCN_WITH_PORT=${CCN_SERVICE}:8080
      - PAYMENT_WITH_PORT=${PAYMENTPROCESSOR_SERVICE}:8080
      - BUSINESSINTEGRATOR_WITH_PORT=${BUSINESSINTEGRATOR_SERVICE}:8080
      - EXTERNALBANK_WITH_PORT=${EXTERNAL_BANK_SERVICE}:8080
      - REDIS_HOST1=gateway-db1
      - REDIS_HOST2=gateway-db2
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql-slave:5432/my_database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=my_database_password
    networks:
      - spring-newbank-network
    
  postgresql-master:
    image: 'docker.io/bitnami/postgresql:11-debian-10'
    environment:
      - POSTGRESQL_PGAUDIT_LOG=READ,WRITE
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_DATABASE=my_database
      - POSTGRESQL_PASSWORD=my_database_password
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - spring-newbank-network
  postgresql-slave:
    image: 'docker.io/bitnami/postgresql:11-debian-10'
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_PGAUDIT_LOG=READ,WRITE
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
    networks:
      - spring-newbank-network

  payment-gateway-authorizer-service-2:
    restart: always
    image: "newbank/payment-gateway-authorizer"
    container_name: "payment-gateway-authorizer-service-2"
    env_file:
      - .env
    ports:
      - "3503:8080"
    depends_on:
      - gateway-db1
      - gateway-db2
      - postgresql-master
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql-master:5432/my_database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=my_database_password
      - CCN_WITH_PORT=${CCN_SERVICE}:8080
      - PAYMENT_WITH_PORT=${PAYMENTPROCESSOR_SERVICE}:8080
      - BUSINESSINTEGRATOR_WITH_PORT=${BUSINESSINTEGRATOR_SERVICE}:8080
      - EXTERNALBANK_WITH_PORT=${EXTERNAL_BANK_SERVICE}:8080
      - REDIS_HOST1=gateway-db1
      - REDIS_HOST2=gateway-db2

    networks:
      - spring-newbank-network
      
  nginx:
    image: nginx:latest
    container_name: "my-nginx"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - payment-gateway-authorizer-service
      - payment-gateway-authorizer-service-2
      - payment-gateway-confirmation-service
      - payment-gateway-confirmation-service-2
    networks:
      - spring-newbank-network
networks:
  spring-newbank-network:
    external: true



